### ISSUE TITLE
Unhandled Exception: System.ComponentModel.Win32Exception: The system cannot find the file specified

### ISSUE THREAD

**Issue by esidegallery** [chebum/Supervisor#4]
The following error is occurring on Windows 10 x64.
```
Unhandled Exception: System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Supervisor.MonitorThread.DoMonitor()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by robertkjr3d** [comment]
I have the same error!!

**Comment by Testerboy21** [comment]
Anyone ever fix this?

**Comment by chebum** [comment]
@Testerboy21 its an open source software. You're free to fix it and make a pull request to merge the changes.

**Comment by jompeterson** [comment]
@esidegallery I had a similar issue. One thing to check for is if the path to the executable has spaces that you need to put 3 quotation marks before the path and two after the end of the path to the executable.

**Comment by TheExpertNoob** [comment]
Try running supervisor with an elevated (administrator) level shell.
